export default {
  apiBaseURL: 'https://api.coinmarketcap.com',

  /* eslint-disable */
  images: {
    ANT: require('../assets/Icons/aragon.png'),
    ARDR: require('../assets/Icons/ardor.png'),
    REP: require('../assets/Icons/augur.png'),
    BCH: require('../assets/Icons/bitcoin-cash.png'),
    BTC: require('../assets/Icons/bitcoin.png'),
    BTG: require('../assets/Icons/bitcoin-gold.png'),
    BCC: require('../assets/Icons/bitconnect.png'),
    BTS: require('../assets/Icons/bitshares.png'),
    BCN: require('../assets/Icons/bytecoin.png'),
    XCP: require('../assets/Icons/counterparty.png'),
    DASH: require('../assets/Icons/dash.png'),
    DCR: require('../assets/Icons/decred.png'),
    DGB: require('../assets/Icons/digibyte.png'),
    DGD: require('../assets/Icons/digixdao.png'),
    DOGE: require('../assets/Icons/dogecoin.png'),
    EMC: require('../assets/Icons/emercoin.png'),
    ETH: require('../assets/Icons/ethereum.png'),
    ETC: require('../assets/Icons/ethereumclassic.png'),
    FCT: require('../assets/Icons/factom.png'),
    GAME: require('../assets/Icons/gamecredits.png'),
    GNO: require('../assets/Icons/gnosis.png'),
    GNT: require('../assets/Icons/golem.png'),
    NLG: require('../assets/Icons/gulden.png'),
    ICN: require('../assets/Icons/iconomi.png'),
    MIOTA: require('../assets/Icons/iota.png'),
    KMD: require('../assets/Icons/komodo.png'),
    LTC: require('../assets/Icons/litecoin.png'),
    LKK: require('../assets/Icons/lykke.png'),
    MAID: require('../assets/Icons/maid.png'),
    MLN: require('../assets/Icons/melon.png'),
    XMR: require('../assets/Icons/monero.png'),
    NMC: require('../assets/Icons/namecoin.png'),
    XEM: require('../assets/Icons/nem.png'),
    NEO: require('../assets/Icons/neo.png'),
    NXT: require('../assets/Icons/nxt.png'),
    PPC: require('../assets/Icons/peercoin.png'),
    POT: require('../assets/Icons/potcoin.png'),
    XRP: require('../assets/Icons/ripple.png'),
    SC: require('../assets/Icons/sia.png'),
    SNGLS: require('../assets/Icons/singulardtv.png'),
    STEEM: require('../assets/Icons/steem.png'),
    XLM: require('../assets/Icons/stellar.png'),
    STRAT: require('../assets/Icons/stratis.png'),
    AMP: require('../assets/Icons/synereo.png'),
    USDT: require('../assets/Icons/tether.png'),
    VTC: require('../assets/Icons/vertcoin.png'),
    WAVES: require('../assets/Icons/waves.png'),
    ZEC: require('../assets/Icons/zcash.png'),
  },
};
